
name: MaskShop
main: MASKshop\Main
api: [3.0.0, 3.0.1, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 1.0
author: PLUGPLUS
Translate: Russian to English by BlazeHub

commands:
 mask:
  aliases: ["maskshop"]
  description: "Buy mask"
